#!/usr/bin/env bash
# A Bash script that resists SIGTERM and prints "I am invincible!!!" instead

trap "echo 'I am invincible!!!'" SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
done
